### ISSUE TITLE
bug in `draw_from_prior`

### ISSUE THREAD

**Issue by paulthebaker** [stevertaylor/enterprise_extensions#3]
at model_utils.py line [132](https://github.com/stevertaylor/enterprise_extensions/blob/master/enterprise_extensions/model_utils.py#L132)

if there are any vector parameters in the model (e.g. free spectral RN, `jup_orb_elements`) then the scalar draws will be scrambled.  The `pta.params` index is different from the `ptmcmc` model dimension index, so `q[idx]` is not the same parameter as `param = pta.params[idx]`.

Proper use of `pmap` will fix this.

**Comment by stevertaylor** [comment]
Great that this was found. Can you submit a PR to resolve this in the usual model and also the HyperModel usage?

**Comment by stevertaylor** [comment]
I guess the CW search has not really been using enterprise_extensions much, but this draw_from_prior function came from lots of code that had been circulating in other places. So it's possible it has shown up in several areas.

**Comment by paulthebaker** [comment]
yeah, according to @kristina-islo the version used in the cw search is identical to `enterprise_extension`.
