### ISSUE TITLE
Cannot pass noise parameters to OptimalStatistic() object

### ISSUE THREAD

**Issue by NihanPol** [stevertaylor/enterprise_extensions#7]
There is no argument to define the noise parameters associated with an OptimalStatistic (OS) object in the current framework. The noise parameters are required further down the line to do any computations with the object.

**Comment by Hazboun6** [comment]
@NihanPol Which noise parameters do you mean here? Is the problem that the PTA object defined with the OS is one specific configuration? If that is the case then pull request #17 might fix this.

**Comment by NihanPol** [comment]
Yes, I think pull request #17 does solve this problem. I'm going to close the issue in that case. Thanks!
