### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by minyoungk99** [stevertaylor/enterprise_extensions#8]
I just tried to import the new version of enterprise extensions, and got the following error.
`File "/astro/users/myk99/anaconda3/lib/python3.6/site-packages/enterprise_extensions/models.py", line 338
    return scipy.stats.invgamma.rvs(scale=gamma, size=size))
    ^
IndentationError: unexpected indent`

**Comment by stevertaylor** [comment]
I believe @Hazboun6 has resolved this. The fixes have been merged. Thanks for flagging this error.
